# ----------------
# Image: fedora
# Docs: https://hub.docker.com/_/fedora
# ----------------

FROM fedora:latest

RUN dnf update -y && \
    dnf install -y https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm && \
    dnf install -y dnf-plugins-core

RUN dnf install -y \
    pciutils-libs \
    dbus-x11 \
    dbus-glib \
    libXt \
    gtk3.x86_64 \
    mesa-libGL.x86_64 \
    mesa-libEGL.x86_64 \
    mesa-dri-drivers.x86_64 \
    pulseaudio \
    alsa-lib \
    wget \
    bzip2 \
    dejavu-sans-fonts \
    libXcursor.x86_64 \
    adwaita-cursor-theme

WORKDIR /home

RUN curl -o firefox.tar.bz2 -LJO "https://download.mozilla.org/?product=firefox-devedition-latest-ssl&os=linux64&lang=en-US" && \
    tar -xvf firefox.tar.bz2

RUN echo "Xcursor.size: 24" >> ~/.Xdefaults && \
    echo "Xcursor.theme: Adwaita" >> ~/.Xdefaults

CMD [ "/bin/sh", "-c", "/home/firefox/firefox" ]
