# ----------------
# Image: alpine
# Docs: https://hub.docker.com/_/alpine
# ----------------

FROM alpine:latest

RUN apk update --no-cache && \
    apk add --no-cache \
    ca-certificates \
    pciutils-libs \
    dbus-x11 \
    mesa-gl \
    mesa-dri-swrast \
    mesa-egl \
    pulseaudio \
    pulseaudio-alsa \
    alsa-lib \
    alsa-plugins-pulse \
    ttf-dejavu \
    curl \
    tar \
    bzip2

WORKDIR /tmp

RUN curl -o firefox.tar.bz2 -LJO "https://download-installer.cdn.mozilla.net/pub/devedition/releases/85.0b9/linux-x86_64/en-US/firefox-85.0b9.tar.bz2" && \
    tar -xvf firefox.tar.bz2

CMD [ "/bin/sh", "-c", "/tmp/firefox/firefox" ]
